// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type AccountInput struct {
	Name string `json:"name"`
}

type Accounts struct {
	Orders []*Order `json:"orders"`
}

type Mutation struct {
}

type Order struct {
	ID          string           `json:"id"`
	Amount      float64          `json:"amount"`
	AccountID   string           `json:"accountId"`
	CreatedAt   string           `json:"createdAt"`
	Description string           `json:"description"`
	LineItems   []*OrderLineItem `json:"lineItems"`
}

type OrderInput struct {
	AccountID string                `json:"accountId"`
	LineItems []*OrderLineItemInput `json:"lineItems"`
}

type OrderLineItem struct {
	ID          string  `json:"id"`
	Amount      float64 `json:"amount"`
	Description string  `json:"description"`
}

type OrderLineItemInput struct {
	ID          string  `json:"id"`
	Amount      float64 `json:"amount"`
	Description string  `json:"description"`
}

type PaginationInput struct {
	Skip int `json:"skip"`
	Take int `json:"take"`
}

type Query struct {
}
